### ISSUE TITLE
virus reported by windows defender

### ISSUE THREAD

**Issue by daiz89** [seto77/ReciPro#32]
![屏幕截图 2024-03-11 095347](https://github.com/seto77/ReciPro/assets/81338433/a8a45cdd-1ee5-4278-8847-819f7fbe86ba)

**Comment by seto77** [comment]
Thank you for your report.
Please wait a moment while I investigate the security problem.

**Comment by seto77** [comment]
daiz89-san, 

The problem seems to be that windows defender is responding incorrectly.
I checked with several virus detection software and found no viruses or malware infections.

Upon further investigation, I found that the (recent?) Windows Defender behaves incorrectly with compressed installation files (msi files).
Therefore, I will release the latest version (ver.4.881) without compression. Please forgive the large file size.
