### ISSUE TITLE
Structure factor

### ISSUE THREAD

**Issue by Taimin** [seto77/ReciPro#39]
Hi,
I found that the result of structure factor calculation for electron is different between CrystDiffract and Recipro. Here comes the cif file:
[NiO.csv](https://github.com/user-attachments/files/17528326/NiO.csv)
The results from CrystDiffract for (200) are given below:
![image](https://github.com/user-attachments/assets/4d17540e-464b-4a48-a91c-c7c4f359bf33)
While the results from Recipro are different:
![image](https://github.com/user-attachments/assets/01b38ac9-5501-4242-b0a4-4ac2776332db)
Could you have a look at it? Thanks a lot.

Best,
Taimin

**Comment by seto77** [comment]
Taimin-san,

Thank you for your report. It is indeed strange.

In CrystalDiffract, what are the values for the structure factors of other crystal planes (e.g. (111) and (220))? If the ratios of these are the same, I think it is simply a matter of how they are normalized.

**Comment by Taimin** [comment]
Hi Seto,
Here comes the Fcalc in CrystDiffract for other crystal planes:
                                                                 F(Re)
![image](https://github.com/user-attachments/assets/fb4a65a3-0aeb-4b05-a311-49fd6dbbfd07)
![image](https://github.com/user-attachments/assets/ba29cb04-d5e1-42f8-a124-04cc8c53bed9)
![image](https://github.com/user-attachments/assets/127d1827-5dda-43af-b1c7-3a07fd2cc36e)
200/111 = 34.3/1.19
200/220 = 34.3/23.0
200/400 = 34.3/17.2
I set all the ADPs to 0. 
200/220 ratio is close but others are not.

Best,
Taimin

**Comment by Taimin** [comment]
I used cctbx to calculate. Seems CrystDiffract has some issues...
![image](https://github.com/user-attachments/assets/835cf455-1953-4651-80f5-f98a38dd6924)

**Comment by seto77** [comment]
The cctbx's results (in angstrom) are in perfect agreement with ReciPro's results (in nm) calculated with zero Debye-Waller factor using neutral atom parameters.
![image](https://github.com/user-attachments/assets/333ed0a1-b244-46cf-acf6-5803cf3590f8)
![image](https://github.com/user-attachments/assets/aaea5efc-bbcd-4cf4-840a-f5332925842f)
![image](https://github.com/user-attachments/assets/45d35f0d-9e33-4feb-9f67-f38c65230199)

Compared to CrystalDiffract, there seems to be a large discrepancy at low angles (i.e., g=111),  possibly because CrystalDiffract treats atoms as ions, not neutrals. I am not a CrystalDiffract user, so I don't know exactly what it is. Sorry.

**Comment by Taimin** [comment]
Oh, I reproduced the same results. I set Uiso to 1 in Recipro and that's why it is deviated from cctbx.
